import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LocaleSwitcher from "components/LocaleSwitcher";
import "@/globals.css";

const notoSerif = Noto_Serif_JP({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  display: "swap",
  variable: '--font-noto-serif',
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Standage Home Assignment",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) => {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <link href="/favicon.ico" rel="icon" />
      </head>
      <body className={notoSerif.variable}>
        <NextIntlClientProvider messages={messages}>
          <header className="fixed top-0 h-16 w-full flex justify-end items-center shadow-lg bg-white px-6">
            <LocaleSwitcher />
          </header>
          <main className="flex min-h-screen flex-col items-center justify-center p-6 pt-16 bg-slate-200">
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
