import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LangSwitcher from "components/LangSwitcher";
import "./globals.css";

const noto = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Standage Home Assignment",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) => {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={noto.className}>
        <NextIntlClientProvider messages={messages}>
          <header className="fixed top-0 h-16 w-full flex justify-end items-center shadow-lg bg-white px-6">
            <LangSwitcher />
          </header>
          <main className="flex min-h-screen flex-col items-center justify-center p-6 pt-16 bg-slate-300">
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
